version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=invjl1290
      - POSTGRES_USER=luisa
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
